version: '3'
services:
  spring-boot-job-service:
    container_name: spring-boot-job-service
    image: personal/spring-boot-job-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_HOST=${HOST_IP} #Public IPv4 address of aws -instance
      - SPRING_DATASOURCE_PORT=5432
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}