server:
  port: 8081
spring:
  application:
    name: spring-boot-job-service
  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}
      fail-fast: false
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"